mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: restaurantdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    ports:
      - 3307:3306